// This file exports the styles from cyber-card.module.css as a default export
// to fix the deployment error

const styles = {
  container: "container",
  canvas: "canvas",
  card: "card",
  "card-content": "card-content",
  prompt: "prompt",
  title: "title",
  subtitle: "subtitle",
  highlight: "highlight",
  "glowing-elements": "glowing-elements",
  "glow-1": "glow-1",
  "glow-2": "glow-2",
  "glow-3": "glow-3",
  "card-particles": "card-particles",
  tracker: "tracker",
  "card-glare": "card-glare",
  "cyber-lines": "cyber-lines",
  "corner-elements": "corner-elements",
  "scan-line": "scan-line",
  "tr-1": "tr-1",
  "tr-2": "tr-2",
  "tr-3": "tr-3",
  "tr-4": "tr-4",
  "tr-5": "tr-5",
  "tr-6": "tr-6",
  "tr-7": "tr-7",
  "tr-8": "tr-8",
  "tr-9": "tr-9",
  "tr-10": "tr-10",
  "tr-11": "tr-11",
  "tr-12": "tr-12",
  "tr-13": "tr-13",
  "tr-14": "tr-14",
  "tr-15": "tr-15",
  "tr-16": "tr-16",
  "tr-17": "tr-17",
  "tr-18": "tr-18",
  "tr-19": "tr-19",
  "tr-20": "tr-20",
  "tr-21": "tr-21",
  "tr-22": "tr-22",
  "tr-23": "tr-23",
  "tr-24": "tr-24",
  "tr-25": "tr-25",
  noselect: "noselect",
}

export default styles

